### ISSUE TITLE
Build issues - opencv - ROS Noetic

### ISSUE THREAD

**Issue by ram-bhaskara** [irapkaist/file_player_mulran#10]
Hi, 

I'm unable to build the source using catkin_make. I'm using ROS Noetic (Ubuntu 20.04). The first issue was catkin_make failed to build opencv/cv.h and opencv/highgui.h (screenshot below)
![image](https://user-images.githubusercontent.com/63920557/193713929-db5743cc-8cb4-4821-87cb-9f9666ba6744.png)

I followed a recommended [fix](https://answers.ros.org/question/398357/catkin_make-failed-to-build-opencv/) but it did not help. I now have a lot more build errors - majority are from member functions (screenshot below). Did you come across these problems? Any suggestions?

![image](https://user-images.githubusercontent.com/63920557/193714237-0cda5af7-cda0-4fed-87be-5ab157de6ae4.png)

**Comment by huawei-sai** [comment]
**Solution**

1. The first issue related to OpenCV occurs because file_player_mulran is compatible with OpenCV 3.x versions while your system might be having OpenCV 4,x version. You have solved it using this solution https://answers.ros.org/question/398357/catkin_make-failed-to-build-opencv/
2. Another solution could be that to install OpenCV 3.x as most SLAM or other packages might be using OpenCV 3.x and that would make life more easier as there wont be any need to make those changes in files from other packages, for example SC-LeGO-LOAM.
3. The second error is caused because latest versions of PCL requires c++14 standard to be defined in the CMakeLists for successful compilation. You can add this `set(CMAKE_CXX_STANDARD 14)` to the CMakeLists.txt of the file_mulran_player and it should solve the issue.

**Comment by minwoo0611** [comment]
Sorry for the late responding.

As many people tackle the same issue, we make a new branch to solve the compile error.

Thank you for giving the solution!
